### ISSUE TITLE
Outsourcing Version Ports

### ISSUE THREAD

**Issue by emanuelal99** [AzureDoom/Dark-Waters#10]
This mod is one of my favorites but the 1.19.3 version isn't updated as frequently as other mods in 1.19.2. Would you consider outsourcing porting versions to other creators? Thanks

**Comment by AzureDoom** [comment]
1.19.2 is not planned until the AI is complete in 1.19.3. It will only be ported back once then. Current focus has been bug fixing another mod (Gigeresque) before moving back to this and Arachnids.
