### ISSUE TITLE
[compatibility issue] Chirpy's Wildlife

### ISSUE THREAD

**Issue by yonatandeneke** [AzureDoom/Dark-Waters#12]
I apologize if you don't handle mod compatibilities. I thought I'd just post this just in case you do.

Mod Link: https://www.curseforge.com/minecraft/mc-mods/chirpys-wildlife
Whenever I launch up the game, it loops on the starting-up screen. Followed by [] characters for every text.
This only happens with Chirpy's Wildlife and Dark-Waters, which both use Geckolib.

Errors should be in latest.log
[latest.log](https://github.com/AzureDoom/Dark-Waters/files/11307238/latest.log)

**Comment by AzureDoom** [comment]
Issue is on Chirpys end of it. AFAIK they are no longer supporting 1.19.2
