### ISSUE TITLE
can't seem to find any of the mobs

### ISSUE THREAD

**Issue by BLV-DES** [AzureDoom/Dark-Waters#14]
i have disabled the "require storm" option in the config and i have not seen a single one of them in the oceans after several days of having the mod installed. is there something else I need to do/change? i simply want them in the game at all times instead of having to wait for a storm

**Comment by AzureDoom** [comment]
Please try with the latest update now!

**Comment by BLV-DES** [comment]
i just tried it, still nothing. i have even waited and looked around in the ocean during thunderstorms and still no mobs appear

**Comment by BLV-DES** [comment]
just tried it, still nothing. i have even waited and looked around in the ocean during thunderstorms and still no mobs appear

**Comment by BLV-DES** [comment]
just tried it, still nothing. i have even waited and looked around in the ocean during thunderstorms and still no mobs appear

**Comment by Xoulious** [comment]
I also can't find any mobs in the latest version

**Comment by AzureDoom** [comment]
Forgot to update this but update to latest release!
