### ISSUE TITLE
Forge Azurelib doesn't contain mod/azure/azurelib/config/formatConfigFormats

### ISSUE THREAD

**Issue by melvinczyk** [AzureDoom/Dark-Waters#18]
[crash-2023-09-04_22.39.22-client.txt](https://github.com/AzureDoom/Dark-Waters/files/12589002/crash-2023-09-04_22.39.22-client.txt)

**Comment by AzureDoom** [comment]
Correct, you shouldn't be using AzureLib Forge for Fabric. Use the Fabric version
