### ISSUE TITLE
[feature request] A config to remove the fog

### ISSUE THREAD

**Issue by Mega-Godzilla3000** [AzureDoom/Dark-Waters#23]
The dark water's creatures are already pretty rare to find in the first place, you have to be in the ocean, while it thunders. Though this helps with the mystery factor of the mod, the fog that comes during thunder will probably drive players away from the ocean. In other words, the fog only serves to keep players away from the one area, during very specific conditions, that they will ever see the mobs.

**Comment by AzureDoom** [comment]
This is not possible due to how the mixin works and is outside the theme of the mod.
