### ISSUE TITLE
not 1 singular

### ISSUE THREAD

**Issue by KidozyGAME** [AzureDoom/Dark-Waters#3]
1. Death sounds are too drawn out

2. sounds aren't mono and are ear splitting (I use sound physics remastered)

**Comment by KidozyGAME** [comment]
both are more of a nitpick

**Comment by AzureDoom** [comment]
1. Fixed in upcoming update.
2. Fixed in upcoming update. 

Sounds got a overhaul in the next update. Just need to finish the needed AI before I release the update.
