### ISSUE TITLE
hitbox

### ISSUE THREAD

**Issue by Rad233** [AzureDoom/Dark-Waters#6]
Excellent work, but some of the mobs' hitbox are so weird--they are all in the shape of square, which makes it extremely hard to attack it with melee weapon, and player would be attacked in a rediculous distance (especially when player is by the side of them). I would appreciate it if you could make the hitbox a little accurate!
I don't have a cureforge account, and this should be in  the commands. But I really couldn't find another way to contact you, sorry!

**Comment by AzureDoom** [comment]
The mobs are unfinished outside of 3. This mod is currently on hold until 1.19 and won't be updated for 1.18.2.
