### ISSUE TITLE
skipped 1.19.2?

### ISSUE THREAD

**Issue by ProducerMZ** [AzureDoom/Dark-Waters#9]
I would absolutely LOVE to add this mod! I always find a shore by the ocean to build my home and build a nice dock for a boat.
What a fantastic idea, adding some much needed concern to the oceans, and just gorgeous mob work!!

That being said, I sincerely hope you will be making a 1.19.2 fabric version of Dark Waters. I've put months of work into that version. 
With two hundred and seventy five 1.19.2 mods, and sixteen resource packs painstakingly balanced for quality and stability, it pains me to think about starting over with just 1.19.3, for what little it offers in return. 

I'd truly hate to miss out on this Dark Waters masterpiece. 
Please let me know if that even interests you. Thanks. - M

**Comment by AzureDoom** [comment]
It's not worth writing for 1.19.2, as I only support the latest .x version as that's what I'm playing. I am returning to modding what I play myself, not what others want.

**Comment by ProducerMZ** [comment]
Sucks to be me, and every other 1.19.2 player I guess. Thanks for letting me down easy.
